<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'stripe.iban.mandate-acceptance-text' => 'Wenn Sie Ihre IBAN angeben und diese Zahlung bestätigen, sind Sie damit einverstanden, dass unser Zahlungsservice Anbieter die Firma Rocketship Inc. und Stripe Ihre Bank anweist Ihr Konto mit dem Kaufpreis zu belasten. Eine Rückerstattung ist innerhalb von 8 Wochen ab dem Datum, an dem Ihr Konto belastet wurde möglich.',
];
