<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ArticleOld ID' => '',
    'Data' => '',
    'Order ID' => '',
    'Qty' => '',
    'Sell Price' => '',
    'Sku' => '',
    'Title' => '',
    '{attribute} is not a valid IBAN No.' => '',
    '{attribute} is not a valid.' => '',
    'Active' => '@@@@',
    'Address ID' => '@@@@',
    'Birthday' => '@@@@',
    'Category ID' => '@@@@',
    'Created At' => '@@@@',
    'Default Qty' => '@@@@',
    'Description' => '@@@@',
    'Email' => '@@@@',
    'Gender' => '@@@@',
    'ID' => '@@@@',
    'Name' => '@@@@',
    'Ordering' => '@@@@',
    'Parent' => '@@@@',
    'Shipping' => '@@@@',
    'Updated At' => '@@@@',
    'User ID' => '@@@@',
];
